[package]
name = "rema"
version = "0.1.0"
authors = ["David Sunshine <david@sunshines.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
float-cmp = "0.8.0"
